### ISSUE TITLE
doesnt work with node 12.1

### ISSUE THREAD

**Issue by rburgst** [cactorium/node-cint64#4]
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node-cint64/src/cint64.o
In file included from ../src/cint64.cc:3:
../src/int64-type.h:12:26: error: no template named 'Handle' in namespace 'v8'
    static void Init(v8::Handle<v8::Object> exports);
                     ~~~~^
../src/int64-type.h:28:37: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
                        v8::String::NewFromUtf8(isolate, "wrong number of arguments"))
                                    ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:36:45: error: no matching member function for call to 'ToObject'
        if (args[0]->IsObject() && args[0]->ToObject()->GetPrototype() == prototype) {
                                   ~~~~~~~~~^~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:37:63: error: no matching member function for call to 'ToObject'
            other = ObjectWrap::Unwrap<Int64Wrapper>(args[0]->ToObject());
                                                     ~~~~~~~~~^~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:39:47: error: no matching member function for call to 'ToInteger'
            other = new Int64Wrapper(args[0]->ToInteger()->Value());
                                     ~~~~~~~~~^~~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2534:45: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Integer> ToInteger(
                                            ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2548:36: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Integer> ToInteger(Isolate* isolate) const);
                                   ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:43:37: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
                        v8::String::NewFromUtf8(isolate, "argument must be a number or a int64 object"))
                                    ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:54:29: error: expected '(' for function-style cast or type construction
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
                   ~~~~~~~~~^
../src/int64-type.h:54:13: error: no member named 'Handle' in namespace 'v8'
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
        ~~~~^
../src/int64-type.h:54:31: error: use of undeclared identifier 'argv'; did you mean 'args'?
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
                              ^~~~
                              args
../src/int64-type.h:22:61: note: 'args' declared here
            F f, const v8::FunctionCallbackInfo<v8::Value>& args) {
                                                            ^
../src/int64-type.h:58:53: error: use of undeclared identifier 'argv'
        auto ret = cons->NewInstance(context, argc, argv).ToLocalChecked();
                                                    ^
../src/int64-type.h:74:29: error: expected '(' for function-style cast or type construction
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
                   ~~~~~~~~~^
../src/int64-type.h:74:13: error: no member named 'Handle' in namespace 'v8'
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
        ~~~~^
../src/int64-type.h:74:31: error: use of undeclared identifier 'argv'; did you mean 'args'?
        v8::Handle<v8::Value> argv[argc] = { v8::Number::New(isolate, 0) };
                              ^~~~
                              args
../src/int64-type.h:66:61: note: 'args' declared here
            F f, const v8::FunctionCallbackInfo<v8::Value>& args) {
                                                            ^
../src/int64-type.h:78:53: error: use of undeclared identifier 'argv'
        auto ret = cons->NewInstance(context, argc, argv).ToLocalChecked();
                                                    ^
../src/int64-type.h:94:45: error: no matching member function for call to 'ToObject'
        if (args[0]->IsObject() && args[0]->ToObject()->GetPrototype() == prototype) {
                                   ~~~~~~~~~^~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:95:63: error: no matching member function for call to 'ToObject'
            other = ObjectWrap::Unwrap<Int64Wrapper>(args[0]->ToObject());
                                                     ~~~~~~~~~^~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:97:47: error: no matching member function for call to 'ToInteger'
            other = new Int64Wrapper(args[0]->ToInteger()->Value());
                                     ~~~~~~~~~^~~~~~~~~
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2534:45: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Integer> ToInteger(
                                            ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2548:36: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Integer> ToInteger(Isolate* isolate) const);
                                   ^
In file included from ../src/cint64.cc:3:
../src/int64-type.h:101:37: warning: 'NewFromUtf8' is deprecated: Use maybe version [-Wdeprecated-declarations]
                        v8::String::NewFromUtf8(isolate, "argument must be a number or a int64 object"))
                                    ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:2890:10: note: 'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/cint64.cc:8:17: error: variable has incomplete type 'void'
    static void Init(Handle<Object> exports, Handle<Object> module) {
                ^
../src/cint64.cc:8:29: error: 'Object' does not refer to a value
    static void Init(Handle<Object> exports, Handle<Object> module) {
                            ^
/Users/rainer/.node-gyp/12.1.0/include/node/v8.h:3356:17: note: declared here
class V8_EXPORT Object : public Value {
                ^
../src/cint64.cc:8:22: error: use of undeclared identifier 'Handle'
    static void Init(Handle<Object> exports, Handle<Object> module) {
                     ^
../src/cint64.cc:8:37: error: use of undeclared identifier 'exports'
    static void Init(Handle<Object> exports, Handle<Object> module) {
                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by cactorium** [comment]
Alrighty, I'll work on getting this working again this weekend

**Comment by cactorium** [comment]
Please update to 3.0.0 and lemme know if that works

**Comment by cactorium** [comment]
It was passing 12 in Travis CI so I'm going to go ahead and close this. If it's still an issue feel free to reopen
